### ISSUE TITLE
Review models and attributes

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/BIOS#116]
Check the "certificates" and "CMS" models and translate the names of the models or attributes into English if they are not.

**Comment by LinaMejia** [comment]
@diferpaho  all the fields in the models from cms app are declared in english. are we going to add the verbose_name attribute and use 'django.utils.translations' for translations or is it okay like it is now?

**Comment by diferpaho** [comment]
At the moment I do not think it is necessary since we are finishing the course and we have little time, but in the future it is something that would be good to implement.
