### ISSUE TITLE
CMS - Implement the models in the carousel

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#119]
Based on the models created, implement these in the base template, specifically in the carousel section.
Additionally, implement your solution from Activity 2 related to the carousel

Please use static information if is neccesary to make sure that works fine.
If you need more information don't hetsaite to let me know

**Comment by diferpaho** [comment]
@soycamilounillanos  Please work as a team with your partner

**Comment by soycamilounillanos** [comment]
Ok I'm going to organize with my teammate

**Comment by juancuero** [comment]
How can I get the id of the current page to bring the corresponding carousel?

**Comment by diferpaho** [comment]
Very well!
