### ISSUE TITLE
Error in loaddata in composer

### ISSUE THREAD

**Issue by romnyd** [encisosystems/BIOS#120]
Hi,  when docker is launched locally, it has the following problem. 

![image](https://user-images.githubusercontent.com/4432320/119240048-f3431f80-bb12-11eb-8911-990e4102cfbd.png)

![image](https://user-images.githubusercontent.com/4432320/119240069-21286400-bb13-11eb-9d32-47ad796be3a0.png)

**Comment by Rohiri** [comment]
@romnyd 

Hey @romnyd, try this


1.  run `docker compose up --build`
2. open new terminal
3. run `make makemigrations` 
4. run `make migrate`

**Comment by diferpaho** [comment]
Hi @romnyd, has your problem with the @Rohiri contribution been solved?

**Comment by romnyd** [comment]
Hi. show this.

![image](https://user-images.githubusercontent.com/4432320/119411832-a7c67800-bcb0-11eb-872d-fd319bc4c4e8.png)

**Comment by Rohiri** [comment]
Hi, @romnyd 

The cms migrations has problems, Fix cms migrations

#proposal fix
carrousel = models.ForeignKey(Carrousel, on_delete=models.CASCADE, null=True)

pull last changes on develop branch to use the command `make migratefake`

**Comment by diferpaho** [comment]
The error should already be solved, verify that you are in development and use the `git pull` command
