### ISSUE TITLE
Certificate - Based in the models created implement it in the certificate letter

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#121]
Please use the models created and implement it in the certificate letters.

If it's neccessary use static information to make your that works fine
Please let me know if you need more information.

**Comment by parejajd** [comment]
Thanks a lot, We really need more time, please 

Working...

 :)

**Comment by parejajd** [comment]
It is the implementation

![image](https://user-images.githubusercontent.com/3516716/120043419-8c6dac80-bfd1-11eb-9281-1f5b0347037e.png)

**Comment by andreaveca** [comment]
Amzing job!
