### ISSUE TITLE
Certificate - Based in the models created implement it for the CMA licence

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#122]
Please use the models created and implement it for the CMA licence

If it's neccessary use static information to make your that works fine
Please let me know if you need more information.

**Comment by BryanHerrera04** [comment]
Hello @andreaveca 
I am doing what is requested, however I have a concern.
I can obtain the data of the Person model, however when requesting other models it is not possible. What alternatives can I make?

With the group of certificates we talked about creating a table of manipulators to be able to access to make your certificate, letter and card. Adjustments were also made to models.
@parejajd @Rohiri @jaev-977 @jorgecuenca 

I attach images and it is uploaded on the branch

_branch_ 

feacture/add-connect-front-back 

_images_

![image](https://user-images.githubusercontent.com/57650676/119771801-dd6f8a80-be83-11eb-856d-caa1ca9a5852.png)

![image](https://user-images.githubusercontent.com/57650676/119771852-efe9c400-be83-11eb-8750-857a0f02055f.png)

![image](https://user-images.githubusercontent.com/57650676/119771894-ff690d00-be83-11eb-999f-cf7e11b6f7dd.png)

_**urls**_
![image](https://user-images.githubusercontent.com/57650676/119772024-2f181500-be84-11eb-87f4-72fb3a83e8c5.png)

_**views**_
![image](https://user-images.githubusercontent.com/57650676/119772089-448d3f00-be84-11eb-918a-338a2b0fb6b7.png)

_**templates**_

![image](https://user-images.githubusercontent.com/57650676/119772462-d006d000-be84-11eb-9a93-02d376491a33.png)

It is an example, here I show the attributes of person, but when interning with another model I cannot.


Stay tuned

**Comment by andreaveca** [comment]
Hi @BryanHerrera04 Could you please confirm me the name branch? I want to check it locally  but I can't see it when I list all the branches.

On the other hand, feel free to create the table or wharever you need but remember that you need the aproval by @diferpaho when you create models and make sure that everything works fine.

**Comment by BryanHerrera04** [comment]
Hello @andreaveca 
Sorry, she didn't upload it. I remain pending

feacture/add-connect-front-back

**Comment by BryanHerrera04** [comment]
These are the changes in models, no problem

![image](https://user-images.githubusercontent.com/57650676/119913225-f5e2b200-bf22-11eb-95f8-f825fb352a1d.png)

**Comment by diferpaho** [comment]
@Jorgecuenca1  Please work as a team with your partner

**Comment by Jorgecuenca1** [comment]
Si señor

**Comment by andreaveca** [comment]
Good Job!
