### ISSUE TITLE
Certificate - Based in the models created implement it for the Medical Certificate

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#123]
Please use the models created and implement it for the Medical Certificate.

Since Hugo is not here, I ask you to work together on this implementation.

If it's neccessary use static information to make your that works fine
Please let me know if you need more information.

**Comment by diferpaho** [comment]
@Jorgecuenca1 @jaev-977  Please work as a team with your partners

**Comment by andreaveca** [comment]
Excellent team work!
