### ISSUE TITLE
Check cms Migrations

### ISSUE THREAD

**Issue by Rohiri** [encisosystems/BIOS#127]
Hi, @LinaMejia 

Can you review cms migrations

#proposal fix
carrousel = models.ForeignKey(Carrousel, on_delete=models.CASCADE, null=True)

**Comment by diferpaho** [comment]
![Captura de Pantalla 2021-05-25 a la(s) 11 13 03 a  m](https://user-images.githubusercontent.com/46627032/119532099-2fac9080-bd4a-11eb-85f6-7db11ebbd482.png)

@LinaMejia please check the error that occurs in some cases when trying to enter the CMS models from the administrator.

- Contents
- Footer descriptions
- Images
- Menus
- Pages

**Comment by diferpaho** [comment]
Very well!
