### ISSUE TITLE
Create test for the views of cma-carnet

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#144]
Please create a test for the view of CMA-Carnet
See the example implemented for the view of home.

Please make this in the correct file. In your case should be located in the following route

> certificate/tests/test_views.py

**Comment by BryanHerrera04** [comment]
Hello @andreaveca 
I have a question, I am working on my windows pc, I download the last changes from develep and when executing the test with the command: python manage.py test, I get an error that it cannot find a library.

![image](https://user-images.githubusercontent.com/57650676/120375808-d364e600-c2e0-11eb-83a8-45238c9cad64.png)


Docker runs first and the requirements have been installed. That specific library was also installed and the same error follows.

Thank you very much, I am pending

**Comment by andreaveca** [comment]
Hi @BryanHerrera04
Did you run docker using the command `docker-compose up -- build`? If you did it try to install the requeriments using `pip install -r requirements.txt`

To check your test use the command `make test` or `make testapp app=certificates`

**Comment by BryanHerrera04** [comment]
Yes Docker is running.
When installing and running what you tell me, the following happens.

![image](https://user-images.githubusercontent.com/57650676/120379116-e5e11e80-c2e4-11eb-84fa-e2d959e31e09.png)

@andreaveca

**Comment by andreaveca** [comment]
@BryanHerrera04 
A classmate had the same problem but he use WSL in VScode to solve the problem and do it the test.
I also use WSL on Windows to avoid this kind of problems

maybe you can check [this page](https://www.it-swarm-es.com/es/windows/make-no-se-reconoce-como-un-comando-interno-o-externo-programa-operativo-o-archivo-por-lotes-windows-7/1045802376/) to looking for a solution

**Comment by BryanHerrera04** [comment]
Hello @andreaveca 
Solve it only by installing the following library:

`choco install make`

I send you evidence of the test

![image](https://user-images.githubusercontent.com/57650676/120419019-34afa800-c327-11eb-9ab4-71ea4412d2d4.png)

![image](https://user-images.githubusercontent.com/57650676/120419062-4abd6880-c327-11eb-8dcf-3b18bd866e78.png)

Do you have to upload the tests carried out or only with these images?

Thank you very much, I am pending

**Comment by andreaveca** [comment]
Please create a PR with your test

**Comment by BryanHerrera04** [comment]
Hello @andreaveca 
I already sent it please review.

Thank you

**Comment by andreaveca** [comment]
good work Bryan!
