### ISSUE TITLE
Upload certificates

### ISSUE THREAD

**Issue by jmencisom** [encisosystems/BIOS#46]
Please scan and upload the certificates we got from the customer.

Make sure to anonymize them before upload them (e.g., blur personal information such names, addresses, ID, etc.)

Thank you.

**Comment by andreaveca** [comment]
Please find the certificates at https://drive.google.com/file/d/1RvcZ7T0gJur3Q-893u5MNiabICYRwSGd/view?usp=sharing

**Comment by jmencisom** [comment]
Cool, Thanks!
