### ISSUE TITLE
Create template base for CMA Licence

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#72]
Please create a template base for CMA Licence

- Expedition date
- Full name
- identification card
- consecutive number
- Professional HQ firm
- Microbiologist Professional Firm

[bios-1.pdf](https://github.com/encisosystems/BIOS/files/6487809/bios-1.pdf)

Note how the information is shown in the attached file

**Comment by BryanHerrera04** [comment]
**Templates** 
_Interfaz_ 
![image](https://user-images.githubusercontent.com/57650676/119203912-ce3ea600-ba59-11eb-9022-5485185ff23a.png)

_Code_
![image](https://user-images.githubusercontent.com/57650676/119203953-e282a300-ba59-11eb-8b9e-bb802ed288ea.png)

I am pending design corrections

Review job @andreaveca 
thanks you!

**Comment by andreaveca** [comment]
Amazing progress @BryanHerrera04 ! Please note that the licence is two-sides.
At the moment the customer has not requested to join the content of the licence, so please divide the content as it is displayed in the PDF.

**Comment by BryanHerrera04** [comment]
_Interfaz_ 
![image](https://user-images.githubusercontent.com/57650676/119210883-7cefe000-ba74-11eb-905b-66395657b705.png)

_Code_
![image](https://user-images.githubusercontent.com/57650676/119210906-9c870880-ba74-11eb-8f30-d7e70367b0f7.png)
![image](https://user-images.githubusercontent.com/57650676/119210920-af014200-ba74-11eb-923f-f27bfb15f514.png)
![image](https://user-images.githubusercontent.com/57650676/119210926-b9bbd700-ba74-11eb-9c22-3fcb80e5bb07.png)

**Comment by BryanHerrera04** [comment]
Hello @andreaveca 
I send you corrections

**Comment by andreaveca** [comment]
Excellent! if you have you own branch for this solution, Could you please make a PR to the Develop branch?

**Comment by BryanHerrera04** [comment]
I don't have a branch. I made the html in another project, where could I add it to the application? In the base file, how it should be located to enter the license

**Comment by andreaveca** [comment]
You should see a template folder under certificates:

![image](https://user-images.githubusercontent.com/61991687/119213598-0956ce80-ba86-11eb-9a8f-0528a2eec4f8.png)

Please let me know if you need anything else

**Comment by BryanHerrera04** [comment]
I already did it, could you please check if everything is fine, thank you very much. @andreaveca

**Comment by andreaveca** [comment]
@BryanHerrera04 Please do the PR to the develop branch

**Comment by BryanHerrera04** [comment]
Done, could you check, please. @andreaveca

**Comment by andreaveca** [comment]
Good job!
