### ISSUE TITLE
Create template base for medical certificate

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#78]
Please create template base for medical certificate
- consecutive number
- Company name
- City
- Dpto

**Personal information**
- Full name
- identification card
- Position
- Age
- Cel
- Address

**Labs**
- Coprologico
- Frotis faringeo
- KOH Nails

**Medical diagnostic**
- description field

**Concept**
- only choice

[bios-3.pdf](https://github.com/encisosystems/BIOS/files/6487847/bios-3.pdf)

Note how the information is shown in the attached file

**Comment by parejajd** [comment]
Hi,

My Pull Request is https://github.com/encisosystems/BIOS/pull/97 

I forgot to document this issue, i am sorry (I hope it's not too late)

**Comment by andreaveca** [comment]
Keep in mind that you must download the changes from the develop branch before doing the PR. Could you please do the PR again?

**Comment by andreaveca** [comment]
Excellent work!
