### ISSUE TITLE
Create basic individual news template

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#80]
Please create  basic individual news template

- Title
- subtitle
- image
- date
- description
- links

**Comment by michael-pardo** [comment]
![image](https://user-images.githubusercontent.com/47837732/119210536-42854380-ba72-11eb-9e26-139e4f8f6b56.png)

![image](https://user-images.githubusercontent.com/47837732/119210542-49ac5180-ba72-11eb-8e1e-7c25b2f925ee.png)

![image](https://user-images.githubusercontent.com/47837732/119210548-4f099c00-ba72-11eb-8f49-e2b15a800b16.png)


![image](https://user-images.githubusercontent.com/47837732/119210575-84ae8500-ba72-11eb-82be-af931ade731c.png)

![image](https://user-images.githubusercontent.com/47837732/119210583-8d06c000-ba72-11eb-8b76-c5892e53544d.png)

![image](https://user-images.githubusercontent.com/47837732/119210650-01416380-ba73-11eb-9360-5247799e2fab.png)

**Comment by michael-pardo** [comment]
Hi @andreaveca can you review this, please

**Comment by andreaveca** [comment]
@michael-pardo Looks cool! Could you please add the date and a Links section?
On the other hand with Category do you mean Images?

**Comment by michael-pardo** [comment]
I added the news category for describe different types of categories.

**Comment by michael-pardo** [comment]
date
![image](https://user-images.githubusercontent.com/47837732/119228572-3aacba00-bad9-11eb-80dc-7cf3bc4796e9.png)

links section
![image](https://user-images.githubusercontent.com/47837732/119228600-52843e00-bad9-11eb-875b-7166f883a831.png)

**Comment by michael-pardo** [comment]
Hi @andreaveca can you review this, please

**Comment by andreaveca** [comment]
@michael-pardo  Please remove the button or border property that the links have and do a PR to the develop branch
