### ISSUE TITLE
Please create latest news list page

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#81]
keep in mind that there are more than 3 news items, create a preview of the last three where the following is observed:

- Title
- Picture
- date
- Description fragment ()

**Comment by AlexanderFuquene** [comment]
![image](https://user-images.githubusercontent.com/11228518/119421922-6e4c3780-bcc5-11eb-9bad-1570a0c04014.png)
![image](https://user-images.githubusercontent.com/11228518/119421932-74daaf00-bcc5-11eb-8afe-295ecd1db1dc.png)
![image](https://user-images.githubusercontent.com/11228518/119421950-7f954400-bcc5-11eb-91e5-4d88c713c854.png)
![image](https://user-images.githubusercontent.com/11228518/119421961-8754e880-bcc5-11eb-8114-d9a260697576.png)
![image](https://user-images.githubusercontent.com/11228518/119421981-90de5080-bcc5-11eb-815f-b24efaa060c7.png)
![image](https://user-images.githubusercontent.com/11228518/119421999-99cf2200-bcc5-11eb-9d12-42628eaafdc5.png)

**Comment by andreaveca** [comment]
Excellent work! 🚀
