### ISSUE TITLE
Create sliding carousel for news and images/banner

### ISSUE THREAD

**Issue by andreaveca** [encisosystems/BIOS#82]
Please create sliding carousel for news and images/banner

**Comment by juancuero** [comment]
[actividad2-part2.docx](https://github.com/encisosystems/BIOS/files/6524855/actividad2-part2.docx)

**Comment by andreaveca** [comment]
Amazing job! This should be added to our page in the next implementation.
In the next activities please add the screenshots in the comments. This will help in the review and also make easier the visualization to the other classmates who want to visualize your solution
