### ISSUE TITLE
Converting models to Django class diagram

### ISSUE THREAD

**Issue by caanmasu** [encisosystems/BIOS#84]
**Converting models to Django class diagram**

I downloaded the Graphviz program for Windows because the console requires C libraries.

**Steps:**

**1.** Activate our virtual environment.

**2.** Install django_extensions
>`pip install django_extensions`

**3.** Go to `BIOS/bios/settings/common.py`
We will append the library we just downloaded within of `DEPENDENCIES_APPS`.
`'django_extensions',`

**4.** The BIOS project has some dependencies that are in the Docker but not in our venv, they must be added or it will not allow us to execute.
>`pip install dj_database_url`
>`pip install psycopg2`

**5.** We are going to install graphviz, which is the one in charge of the graph display library. But we will not do it by command because in the environment we do not have the C dependencies that are required.
Installation is done by Windows.
[](https://www.graphviz.org/download/#windows)
**IMPORTANT:** at the end of the installation you must check the box to add to the environment variable so that the application can execute commands.

**6.** You need to restart the console for the environment variables to load.

**7.** Install pydot, which is a Graphviz module for Python with which you make the diagrams of the models.
>`pip install pydot`

**8.** Generate the class diagram. It must be inside the BIOS folder
>`py manage.py graph_models -a -g -o bios_graph.png`

The file is generated in the current folder (BIOS)
It will appear that fonts (perhaps) are missing but we are going to omit it.

**Screenshot:**

![bios_graph](https://user-images.githubusercontent.com/17111779/118415683-75de6180-b671-11eb-9b9c-811c67acbe8c.png)

**Comment by jmencisom** [comment]
What a good contribution! Well done

**Comment by jmencisom** [comment]
@caanmasu please generate class diagrams for Certificates, CMS and Shop applications.

Thanks!

**Comment by caanmasu** [comment]
Update: 28/05/2021 1:51 p.m
Branch: master

App certificates

![certificates](https://user-images.githubusercontent.com/17111779/120031393-5c68de00-bfbe-11eb-8a37-bcd79bd5baa2.png)

App cms

![cms](https://user-images.githubusercontent.com/17111779/120031411-61c62880-bfbe-11eb-843f-257793efaa63.png)


App shop

![shop](https://user-images.githubusercontent.com/17111779/120031441-6ee31780-bfbe-11eb-90d7-fbe66616818f.png)



[Full download](https://postimg.cc/MfwPXLY4https://postimg.cc/MfwPXLY4)

**Comment by jmencisom** [comment]
Thanks Camilo.
